;; EULER #045
;; ==========
;; Triangle, pentagonal, and hexagonal numbers are generated by the 
;; following formulae:
;;
;;    Triangle      T[n]=n(n+1)/2     1, 3, 6, 10, 15, ...
;;    Pentagonal    P[n]=n(3n1)/2     1, 5, 12, 22, 35, ...
;;    Hexagonal     H[n]=n(2n1)       1, 6, 15, 28, 45, ...
;;
;; It can be verified that T[285] = P[165] = H[143] = 40755.
;;
;; Find the next triangle number that is also pentagonal and hexagonal.
;;

(ns euler045
  (:use [util.misc]))

(defn solve []
  (->> hexagonal-numbers
       (drop-while #(<= % 40755))
       (filter is-pentagonal?)
       first))

(time (solve))
