;; EULER #044
;; ==========
;; Pentagonal numbers are generated by the formula, P[n]=n(3n-1)/2. The 
;; first ten pentagonal numbers are:
;;
;;     1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
;;
;; It can be seen that P[4] + P[7] = 22 + 70 = 92 = P[8]. However, their
;; difference, 70 - 22 = 48, is not pentagonal.
;;
;; Find the pair of pentagonal numbers, P[j] and P[k], for which their sum 
;; and difference is pentagonal and D = |P[k] - P[j]| is minimised; what is
;; the value of D?
;;

(ns euler044
  (:use [util.misc]))

(defn pentagonal-num [n] 
  (/ (* n (dec (* 3 n))) 2))

(defn solve []
  (first
    (for [j integers
          k (range 1 (inc j))
          :let [pj (pentagonal-num j)
                pk (pentagonal-num k)
                sum  (+ pj pk)
                diff (abs (- pj pk))]
          :when (and 
                  (is-pentagonal? diff)
                  (is-pentagonal? sum))]
      diff)))

(time (solve))
